"""Ephemeral pivot agent (H3) — single-shot, TTL-budgeted inference (blueprint Part 9.3).

A pivot agent is born with:
  * a scoped prompt (string generated by the Watcher using the exhibit template)
  * a list of exhibits (dicts with `exhibit_id`, `sha256`, `summary`, ...)
  * a TTL budget (ms) and a max depth index

It calls `InferenceFacade.pivot_infer()` once, validates the output against the
`PivotFinding` outlines schema, and returns a dict suitable for emitting on
`fractal.report` ZMQ PUSH. On TTL expiry it returns a `terminated_by_ttl` sentinel
so the Watcher can record the event and increment metrics.

The agent NEVER writes to the ledger or pheromones directly — those are writer-
process responsibilities.
"""

from __future__ import annotations

import time
from typing import Any

import anyio
import blake3
import msgspec

from findevil.config.settings import settings
from findevil.inference.facade import InferenceFacade
from findevil.inference.outlines_schemas import PivotFinding, validate_pivot_citations
from findevil.ledger.schema import ArtifactRef, ArtifactType, ReasoningMethod, ReasoningStep
from findevil.ledger.writer import LedgerWriter
from findevil.observability.logging import get_logger
from findevil.observability.metrics import (
    FRACTAL_TTL_EXCEEDED,
    INFERENCE_LATENCY,
)

log = get_logger("findevil.fractal.agent")


class PivotSpawn(msgspec.Struct, kw_only=True, frozen=True):
    """Frame shape written to ZMQ `fractal.spawn`."""

    spawn_id: str
    seed_technique: str | None = None
    scoped_prompt: str
    exhibits: list[dict[str, Any]]
    ttl_ms: int = 2000
    depth: int = 0
    parent_id: str | None = None


class PivotReport(msgspec.Struct, kw_only=True):
    spawn_id: str
    parent_id: str | None
    depth: int
    ok: bool
    terminated_by_ttl: bool
    wallclock_ms: float
    finding: dict[str, Any] | None = None
    error: str | None = None


async def run_pivot(
    spawn: PivotSpawn, *, facade: InferenceFacade | None = None
) -> PivotReport:
    """Execute one pivot. Enforces TTL via anyio.move_on_after.

    Returns a PivotReport (never raises for normal inference errors — they are
    recorded in report.error so the Watcher can still emit telemetry).
    """
    started = time.perf_counter_ns()
    _facade = facade or InferenceFacade()
    report = PivotReport(
        spawn_id=spawn.spawn_id,
        parent_id=spawn.parent_id,
        depth=spawn.depth,
        ok=False,
        terminated_by_ttl=False,
        wallclock_ms=0.0,
    )
    try:
        with anyio.move_on_after(spawn.ttl_ms / 1000.0) as scope:
            t0 = time.perf_counter_ns()
            finding: PivotFinding = await _facade.pivot_infer(
                spawn.scoped_prompt, spawn.exhibits
            )
            validate_pivot_citations(finding, spawn.exhibits)
            await asyncio_to_thread_append_finding(spawn, finding)
            INFERENCE_LATENCY.labels(role="pivot").observe(
                (time.perf_counter_ns() - t0) / 1e9
            )
            report.finding = finding.model_dump()
            report.ok = True
        if scope.cancelled_caught:
            report.terminated_by_ttl = True
            FRACTAL_TTL_EXCEEDED.inc()
    except Exception as e:  # any runtime/validation error
        report.error = f"{type(e).__name__}: {e}"
        log.exception("pivot_agent_error", spawn_id=spawn.spawn_id)
    finally:
        if facade is None:
            try:
                await _facade.close()
            except Exception:
                pass
        report.wallclock_ms = (time.perf_counter_ns() - started) / 1e6
    return report


def _artifact_type(value: str) -> ArtifactType:
    try:
        typ = ArtifactType(value)
    except ValueError:
        typ = ArtifactType.YARA_MATCH
    if typ == ArtifactType.FILE:
        return ArtifactType.YARA_MATCH
    return typ


def _refs_from_finding(spawn: PivotSpawn, finding: PivotFinding) -> list[ArtifactRef]:
    exhibits = {
        str(e.get("exhibit_id")): e for e in spawn.exhibits if isinstance(e, dict)
    }
    refs: list[ArtifactRef] = []
    for ref in finding.evidence_refs:
        exhibit = exhibits.get(ref.exhibit_id, {})
        sha = ref.sha256 or exhibit.get("sha256")
        typ = ArtifactType.FILE if sha else _artifact_type(finding.artifact_type)
        kwargs: dict[str, Any] = {
            "type": typ,
            "uri": str(
                exhibit.get("artifact_uri")
                or exhibit.get("uri")
                or finding.artifact_uri
                or ref.exhibit_id
            ),
            "extra": {"exhibit_id": ref.exhibit_id},
        }
        if sha:
            kwargs["sha256"] = str(sha)
        refs.append(ArtifactRef(**kwargs))
    return refs or [
        ArtifactRef(
            type=_artifact_type(finding.artifact_type),
            uri=finding.artifact_uri,
            extra={"spawn_id": spawn.spawn_id},
        )
    ]


def _append_finding(spawn: PivotSpawn, finding: PivotFinding) -> None:
    writer = LedgerWriter(
        settings.ledger.sqlite_path,
        settings.ledger.ed25519_sk_path,
        settings.ledger.ed25519_pk_path,
    )
    try:
        writer.append(
            agent_id=f"fractal.{spawn.spawn_id[:8]}",
            agent_version="0.1.0",
            agent_model_hash=blake3.blake3(settings.inference.model_name.encode()).hexdigest(),
            host_id=settings.host_id,
            evidence_refs=_refs_from_finding(spawn, finding),
            primary_artifact_key=finding.artifact_uri,
            confidence=finding.confidence,
            severity="medium" if finding.verdict == "evil" else "informational",
            mitre=[t for t in finding.mitre_attack_technique if t.startswith("T")],
            reasoning_trace=[
                ReasoningStep(
                    step_index=0,
                    claim=finding.reasoning,
                    method=ReasoningMethod.LLM_INFERENCE,
                    confidence=finding.confidence,
                    params={
                        "spawn_id": spawn.spawn_id,
                        # lineage: parent_id links this pivot to the finding/pivot
                        # that seeded it, and seed_technique is the ATT&CK technique
                        # that triggered the pivot — so the autonomous re-sequencing
                        # chain (finding → seeded pivot → deeper pivot, depth 0→max)
                        # is fully reconstructable from the signed ledger.
                        "parent_id": spawn.parent_id or "",
                        "seed_technique": spawn.seed_technique or "",
                        "depth": str(spawn.depth),
                        "verdict": finding.verdict,
                        "declared_ignorance": str(finding.declared_ignorance),
                    },
                )
            ],
        )
    finally:
        writer.close()


async def asyncio_to_thread_append_finding(
    spawn: PivotSpawn, finding: PivotFinding
) -> None:
    import asyncio

    try:
        await asyncio.to_thread(_append_finding, spawn, finding)
    except Exception:
        log.exception("fractal_ledger_append_failed", spawn_id=spawn.spawn_id)
